version: '3'

services:
  web:
    image: nginx
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./webserver/html:/usr/share/nginx/html
      - ./webserver/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/nginx/conf.d:/etc/nginx/conf.d
