version: '3'

services:
  web:
    image: nginx
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./site/html:/usr/share/nginx/html
      - ./site/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site/nginx/conf.d:/etc/nginx/conf.d
