---
- name: First palybook
  hosts: all
  become: yes

  vars:
    script_name: "test4"

  tasks:

  - name: Folders creation
    file: 
      path: "{{ item }}"
      state: directory
    loop:  
      - /opt/local/scripts
      - /opt/local/configs

  - name: Creating an empty file
    file:
      path: "/opt/local/scripts/test1.sh"
      state: touch    

  - name: Creating a file with content
    copy:
      dest: "/opt/local/scripts/test2.sh"
      content: |
        #!/bin/bash
        echo "hello world - script => test2"
      mode: 0755

  - name: Add text to a file
    lineinfile: 
      dest: "/opt/local/scripts/test1.sh"
      line: '{{ item }}'
    with_items:
    - '#!/bin/bash'
    - 'echo "hello world - script => test1"'

  - name: Generate file with template
    template: src=templates/example.j2 dest=/opt/local/scripts/{{ script_name }}.sh




